########################################################################################
#|------------------------------------------------------------------------------------|#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|                                  __   __   __      __   __            _____        |#
#|        |__/ | |    |       |\/| /  \ |__) /__`    /  ` /  \ |  | |\ |   |          |#
#|        |  \ | |___ |___    |  | \__/ |__) .__/    \__, \__/ \__/ | \|   |          |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|      Youtube:      www.youtube.com/@davigamer1614                                  |#
#|      Github:       https://github.com/BEAMONDO/Kill-Mobs-Count                     |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|------------------------------------------------------------------------------------|#
########################################################################################

Config:
    mensaje-bienvenida: true
    mensaje-bienvenida-texto: "&6&lBienvenido al &4&lServidor &a&l %player%"
