########################################################################################
#|------------------------------------------------------------------------------------|#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|                                  __   __   __      __   __            _____        |#
#|        |__/ | |    |       |\/| /  \ |__) /__`    /  ` /  \ |  | |\ |   |          |#
#|        |  \ | |___ |___    |  | \__/ |__) .__/    \__, \__/ \__/ | \|   |          |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|      Youtube:      www.youtube.com/@davigamer1614                                  |#
#|      Github:       https://github.com/BEAMONDO/Kill-Mobs-Count                     |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|------------------------------------------------------------------------------------|#
########################################################################################

Config:

    #Envia un mensaje al jugador cuando entra al servidor
    mensaje-bienvenida: true

    #Ir al spawn cuando un jugador entra al servidor
    tp-spawn-al-entrar: true

    #Envia un mensaje al jugador cuando duerme en la cama
    mensaje-dormir: false

    #Envia un mensaje cuando despiertas en la cama
    mensaje-despertar: false
    #Usa un comando cuando despiertas en la cama
    comando-despertar: false
    comando-despertar-usar: kills
    
    